#lang scheme
(require scheme/tcp)
(require "utilities.ss")
(define (send-to-server name-string code-string server port)
  (let-values ([(server->me me->server)
                (tcp-connect server port)])
    (write name-string me->server) 
    (write code-string me->server)
    (close-output-port me->server)
    (let ([response (read server->me)])
      (display response) (newline)
      (close-input-port server->me))))
